name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Run test
      uses: tj-actions/puppeteer@v3.2
      with:
        args: yarn test
